### ISSUE TITLE
how to compile?

### ISSUE THREAD

**Issue by kompowiec** [SoniEx2/torxchat#5]
I attempted to write a PKGBUILD for Arch Linux by following the official documentation. However, I encountered some difficulties and was unable to get it to work as expected.

Would you be so kind as to provide detailed instructions or guidance on how to proceed?

Thank you very much for your assistance.

**Comment by SoniEx2** [comment]
the PKGBUILD from the repos (or hexchat-git from the AUR) *should* still work (assuming you change the sources ofc). updated docs are on the todo list...

**Comment by kompowiec** [comment]
ach, right. I tried use from pacman not AUR, everything is clear. Thanks.
